[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32dev
framework = espidf
build_flags =
    -std=gnu++17
lib_deps =
    https://github.com/ESPressio-Development-Platform/ESPressio-OTA.git#ota_v1
    https://github.com/ESPressio-Development-Platform/ESPressio-Platform-ESP-IDF.git#ota_v1
